### ISSUE TITLE
Cheques error on 1.19

### ISSUE THREAD

**Issue by Fummowo** [Bilicraft-Community/GemsEconomy#3]
I am using the latest build of Paper 1.19 (58), latest release on the Plugin on [spigotmc.org](https://www.spigotmc.org/resources/95658/) and default configuration.

When Executing the command `/cheque write <value>` I am told:
> An internal error occurred while trying to perform this command

This is the output from the console:
> [03:59:50 INFO]: Fummo issued server command: /cheque write 2
[03:59:50 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cheque' in plugin GemsEconomy v4.9.3-GCRemake-1.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2147) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-10]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Item cannot be null
        at org.apache.commons.lang.Validate.noNullElements(Validate.java:364) ~[commons-lang-2.6.jar:2.6]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventory.addItem(CraftInventory.java:292) ~[paper-1.19.jar:git-Paper-10]
        at me.xanium.gemseconomy.commands.ChequeCommand.onCommand(ChequeCommand.java:103) ~[GemsEconomy-4.9.3-GCRemake-1.6.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 17 more

It might be related to the fact that GemsEconomy says "Unknown sub-command" when using just `/cheque write`

Thank you for you work on this remake! I would really like to use it for cheques on my smp :)

**Comment by Ghost-chu** [comment]
Please upload your GemsEconomy cheque configuration, seems it caused by bad configure.
